apiVersion: v2
name: kube-prometheus-stack
description: Prometheus Operator + Prometheus + Grafana + Alertmanager
type: application
version: 1.0.0
appVersion: "0.76.0"

dependencies:
  - name: kube-prometheus-stack
    version: 65.x
    repository: https://prometheus-community.github.io/helm-charts
