apiVersion: v2
name: traefik-wrapper
description: A Helm chart for Traefik Proxy (Latest v3)
type: application
version: 1.0.0
appVersion: "3.3.4"
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"

dependencies:
  - name: traefik
    version: "34.2.0"
    repository: "https://traefik.github.io/charts"
